apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.agentId }}-secret
type: Opaque
stringData:
  BOT_TOKEN: {{ .Values.secrets.botToken | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
  OPENAI_ENDPOINT: {{ .Values.secrets.openaiEndpoint | quote }}
